export interface Post {
  statementDate: string,
  divorceDate: string,
  priorStatement: string,
  birthdate: string,
  otherBirthDate: string,
  marriageDate: string,
  separationDate: string,
   causeAction: string,
   custody: string,
   parentingTime: string,
   alimony: string,
   childSupport: string,
   equitableDistribution: string,
   counselFees: string,
   college: string,
   other: string,
   yourName: string,
   streetAddress: string,
   city: string,
   state: string,
   secondParty: string,
   secondAddress: string,
   secondCity: string,
   secondState: string,
   childOne: string,
   addressOne: string,
   birthOne: string,
   personOne: string,
   childTwo: string,
   addressTwo: string,
   birthTwo: string,
   personTwo: string,
   employerName:string,
   employerAddress:string,
   employerNameTwo:string,
   employerTwoAddress:string,
}
